server:
  port: 8090

spring:
  config:
    import: "classpath:database.yml"

  datasource:
    driver-class-name: ${DB_DRIVER_CLASS}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret:
    key: asjdklasjdklasdjaksldjaskldjaskldqmklwmklnczxkcnpqosenpoeno