server:
  port: 8080

spring:
  config:
    import: "classpath:database.yml"

  datasource:
    driver-class-name: ${DB_DRIVER_CLASS}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000

jwt:
  secret:
    key: asjdklasjdklasdjaksldjaskldjaskldqmklwmklnczxkcnpqosenpoeno

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

